name: nightcore-auth-service

networks:
  nightcore-network:
    name: nightcore-network
    driver: bridge
    external: true

services:
  nightcore-auth-service:
    image: nightcore-auth-service:latest
    container_name: nightcore-auth-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    env_file:
      - .env

    volumes:
      - ./src/:/app/src/
      - ./main.py:/app/main.py

    depends_on:
      - nightcore-auth-redis

    networks:
      - nightcore-network

    ports:
      - "${API_PORT}:${API_PORT}"

  nightcore-auth-redis:
    image: redis:7-alpine
    container_name: nightcore-auth-redis
    restart: no
    env_file:
      - .env

    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

    networks:
      - nightcore-auth

  nightcore-auth-redisinsight:
    image: redis/redisinsight:latest
    container_name: nightcore-auth-redisinsight
    restart: no
    env_file:
      - .env

    ports:
      - "${REDIS_INSIGHT_PORT}:${REDIS_INSIGHT_PORT}"

    volumes:
      - ./.redisinsight:/data

    depends_on:
      nightcore-auth-redis:
        condition: service_healthy

    networks:
      - nightcore-auth
